### ISSUE TITLE
UnicodeDecodeError Query

### ISSUE THREAD

**Issue by akibzaman** [google-research/plur#5]
During following the installation process I faced errors showing...

> ' UnicodDecodeError: 'charmap [while running 'Read all raw data']' codec can't decode byte 0x8d in position 2625450: character maps to <unidentified>

I am attaching the screenshot for convenience. I am not sure if this is a problem in my device. I am running the code in a Windows OS. 

Is it a problem regarding the OS? Do I have to use a Linux based OS to run PLUR (or is it recommended?). 

Thank You
![01](https://user-images.githubusercontent.com/55422467/161081470-abe339e7-3373-4e84-ac15-6836213a9185.JPG).

**Comment by smoitra87** [comment]
Him @akibzaman , unfortunately we haven't tested on WindowsOS and it's unlikely we'll get to that soon. We would recommend that you run it on linux.

**Comment by akibzaman** [comment]
Thanks a lot for the prompt reply. I will test it on linux then.
